// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Example
{

public enum Any : byte
{
 NONE = 0,
 Monster = 1,
 TestSimpleTableWithEnum = 2,
 MyGame_Example2_Monster = 3,
};

public class AnyUnion
{
  public Any Type { get; set; }
  public object Value { get; set; }
  public MonsterT AsMonster(){ return Type == Any.Monster ? (MonsterT)Value : null; }
  public TestSimpleTableWithEnumT AsTestSimpleTableWithEnum(){ return Type == Any.TestSimpleTableWithEnum ? (TestSimpleTableWithEnumT)Value : null; }
  public MyGame.Example2.MonsterT AsMyGame_Example2_Monster(){ return Type == Any.MyGame_Example2_Monster ? (MyGame.Example2.MonsterT)Value : null; }
  public static object UnPack(object obj, Any type){
    switch(type) {
    case Any.NONE: return null;
    case Any.Monster: return ((Monster)obj).UnPack();
    case Any.TestSimpleTableWithEnum: return ((TestSimpleTableWithEnum)obj).UnPack();
    case Any.MyGame_Example2_Monster: return ((MyGame.Example2.Monster)obj).UnPack();
    default: return null;
    }
  }}


}
